/// Flutter icons LudoIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  LudoIcons
///      fonts:
///       - asset: fonts/LudoIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class LudoIcons {
  LudoIcons._();

  static const _kFontFam = 'LudoIcons';

  static const IconData data_partida = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData partida = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData jogos = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData historico = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData blog = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData alunos = const IconData(0xe805, fontFamily: _kFontFam);
}
